export default [
  { title: 'Paris' },
  { title: 'Lyon' },
  { title: 'Marseille' },
  { title: 'Toulouse' },
  { title: 'Nice' },
  { title: 'Nantes' },
  { title: 'Montpellier' },
  { title: 'Strasbourg' },
  { title: 'Bordeaux' },
  { title: 'Lille' },
  { title: 'Rennes' },
  { title: 'Reims' },
  { title: 'Toulon' },
  { title: 'Saint Etienne' },
  { title: 'Grenoble' },
  { title: 'Dijon' },
  { title: 'Angers' },
  { title: 'Nîmes' },
  { title: 'Clermont-Ferrand' },
  { title: 'Le Mans' },
  { title: 'Aix-en-Provence' },
  { title: 'Brest' },
  { title: 'Tours' },
  { title: 'Amiens' },
  { title: 'Limoges' },
  { title: 'Annecy' },
  { title: 'Perpignan' },
  { title: 'Besançon' },
  { title: 'Metz' },
  { title: 'Orléans' },
  { title: 'Rouen' },
  { title: 'Mulhouse' },
  { title: 'Cean' },
  { title: 'Nancy' },
  { title: 'Roubaix' },
  { title: 'Tourcoing' },
  { title: 'Nanterre' },
  { title: 'Avignon' },
  { title: 'Poitiers' },
  { title: 'Dunkerque' },
  { title: 'Béziers' },
  { title: 'Pau' },
  { title: 'La Rochelle' },
  { title: 'Cannes' },
  { title: 'Calais' },
  { title: 'Antibes' },
  { title: 'Ajaccio' },
  { title: 'Valence' },
  { title: 'Pessac' },
  { title: 'Quimper' },
  { title: 'Chambéry' },
  { title: 'Lorient' },
  { title: 'Narbonne' },
  { title: 'Hyères' },
  { title: 'Bastia' },
  { title: 'Megève' },
  { title: 'Avoriaz' },
  { title: 'Courchevel' },
  { title: 'L\'Alpe d\'Huez' },
  { title: 'Biarritz' },
];
